stages:
- name: maven compile
  steps:
  - runScriptConfig:
      image: java:8
      shellScript: ./mvnw clean package
- name: docker build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: edu.fly.spring-demo
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
